baseURL = "https://www.gilbertandanje.com/"
languageCode = "en-us"
title = "Gilbert Andanje"

theme = "butterick"


# Main navigation which appears below site header
[[menu.main]]
name = "About"
url = "/about/"
weight = 1


# Homepage settings

[params]
  abbrDateFmt = "Jan 2"
  dateFmt = "2006-01-02"
  subtitle = "Software Engineer"
  author = "Gilbert Andanje"
  customStylesheets = ["css/custom.css"]
  brandIconFile = "images/brand.png"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/andanje122334/"

[[params.social]]
  name = "github"
  link = "https://github.com/GAndanje"

[[params.social]]
  name = "email"
  link = "gilbertandanje@gmail.com"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4